{{- if .Values.backend.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "automata-app.fullname" . }}-backend
  namespace: {{ include "automata-app.namespace" . }}
  labels:
    {{- include "automata-app.backend.labels" . | nindent 4 }}
  {{- with .Values.backend.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
  - name: http
    port: {{ .Values.backend.service.port }}
    targetPort: http
    protocol: TCP
  {{- if .Values.monitoring.enabled }}
  - name: metrics
    port: 9090
    targetPort: metrics
    protocol: TCP
  {{- end }}
  selector:
    {{- include "automata-app.backend.selectorLabels" . | nindent 4 }}
{{- end }}

{{- if .Values.frontend.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "automata-app.fullname" . }}-frontend
  namespace: {{ include "automata-app.namespace" . }}
  labels:
    {{- include "automata-app.frontend.labels" . | nindent 4 }}
  {{- with .Values.frontend.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
  - name: http
    port: {{ .Values.frontend.service.port }}
    targetPort: http
    protocol: TCP
  selector:
    {{- include "automata-app.frontend.selectorLabels" . | nindent 4 }}
{{- end }}